/**
 * Dashboard Component
 * 
 * Central hub for farmers to view and manage their farming operations.
 * This component orchestrates multiple data sources and provides a comprehensive
 * overview of the farmer's activities, finances, weather, and AI-powered insights.
 * 
 * Key Features:
 * - Real-time weather display based on user location
 * - Active crop tracking and management
 * - Financial summary (income, expenses, net profit)
 * - AI-generated personalized farming insights
 * - Quick action buttons for common tasks
 * - Integration with multiple dialogs (Add Crop, Add Ledger Entry, Yield Calculator)
 * 
 * Data Sources:
 * - profiles table: User profile information and location
 * - crops table: User's active crop plantings
 * - ledger table: Financial transactions (income/expenses)
 * - fetch-weather edge function: Real-time weather data
 * - ai-insights edge function: Personalized AI recommendations
 * 
 * State Management:
 * - Profile data: User's name and location
 * - Weather data: Current conditions for user's location
 * - Crops data: List of active crop plantings
 * - Ledger summary: Aggregated financial totals
 * - Dialog states: Open/close states for various dialogs
 * - AI insights: Array of personalized recommendations
 */

import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Plus, Calculator, BookOpen, TrendingUp, Cloud, Droplets, Wind, Loader2, Sparkles, DollarSign } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useNavigate } from "react-router-dom";
import AIChatbot from "@/components/AIChatbot";
import AddCropDialog from "@/components/AddCropDialog";
import AddLedgerDialog from "@/components/AddLedgerDialog";
import YieldCalculatorDialog from "@/components/YieldCalculatorDialog";
import MyProduce from "@/components/MyProduce";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from "recharts";

/**
 * Profile Data Interface
 * Contains basic user information fetched from profiles table
 */
interface Profile {
  full_name: string;  // User's full name for personalized greeting
  location: string;   // User's location/region for weather and market data
}

/**
 * Crop Data Interface
 * Represents a single crop planting by the farmer
 */
interface Crop {
  id: string;           // Unique crop record identifier
  crop_name: string;    // Type of crop (e.g., "Maize", "Tomatoes")
  planting_date: string; // When the crop was planted (ISO date string)
  acreage: number;      // Land area used for this crop
  status: string;       // Crop status: "active", "harvested", etc.
}

/**
 * Ledger Summary Interface
 * Aggregated financial data calculated from ledger table
 */
interface LedgerSummary {
  totalIncome: number;   // Sum of all income transactions
  totalExpenses: number; // Sum of all expense transactions
  // Net profit is calculated as: totalIncome - totalExpenses
}

const Dashboard = () => {
  // ========================================
  // STATE MANAGEMENT
  // ========================================
  
  // User profile data containing name and location
  // Used for: personalized greeting, weather lookup, regional data filtering
  const [profile, setProfile] = useState<Profile | null>(null);
  
  // Current weather data for user's location
  // Structure: { temp, humidity, condition, windSpeed }
  // Fetched from fetch-weather edge function via external weather API
  const [weather, setWeather] = useState<any>(null);
  
  // Loading state for weather data
  // Shows loading spinner while weather is being fetched
  const [weatherLoading, setWeatherLoading] = useState(true);
  
  // Array of user's active crop plantings
  // Filtered to show only status="active" crops (excludes harvested)
  const [crops, setCrops] = useState<Crop[]>([]);
  
  // Aggregated financial totals from ledger table
  // Calculated by summing all income and expense transactions
  const [ledgerSummary, setLedgerSummary] = useState<LedgerSummary>({ 
    totalIncome: 0, 
    totalExpenses: 0 
  });
  
  // Dialog visibility states
  // Control open/close state for modal dialogs
  const [addCropOpen, setAddCropOpen] = useState(false);           // Add new crop dialog
  const [addLedgerOpen, setAddLedgerOpen] = useState(false);       // Add financial entry dialog
  const [yieldCalculatorOpen, setYieldCalculatorOpen] = useState(false); // Yield calculator dialog
  
  // AI-generated personalized insights
  // Array of actionable recommendations based on user's data
  // Generated by ai-insights edge function using Lovable AI
  const [aiInsights, setAiInsights] = useState<string[]>([]);
  
  // Utility hooks
  const { toast } = useToast();     // Toast notifications for user feedback
  const navigate = useNavigate();   // Navigation for routing to other pages

  /**
   * Component Initialization Effect
   * Runs once on component mount to fetch all initial data
   * 
   * Execution order:
   * 1. fetchProfile() - Gets user profile (triggers weather fetch)
   * 2. fetchCrops() - Loads active crop plantings
   * 3. fetchLedgerSummary() - Calculates financial totals
   * 4. fetchAIInsights() - Generates personalized recommendations
   * 
   * All fetches run in parallel for optimal performance
   */
  useEffect(() => {
    fetchProfile();
    fetchCrops();
    fetchLedgerSummary();
    fetchAIInsights();
  }, []);

  // ========================================
  // DATA FETCHING FUNCTIONS
  // ========================================

  /**
   * Fetch User Profile
   * 
   * Retrieves the current user's profile information from the profiles table.
   * This includes their name and location which are used throughout the dashboard.
   * 
   * Side Effects:
   * - Sets profile state with user data
   * - Triggers weather fetch using user's location
   * 
   * Dependencies: Supabase auth (requires authenticated user)
   */
  const fetchProfile = async () => {
    // Get currently authenticated user
    const { data: { user } } = await supabase.auth.getUser();
    
    if (user) {
      // Fetch user's profile data from profiles table
      const { data } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", user.id)
        .single(); // Expect exactly one profile per user
      
      if (data) {
        setProfile(data);
        // Immediately fetch weather for user's location
        // Weather is critical for daily farming decisions
        fetchWeather(data.location);
      }
    }
  };

  /**
   * Fetch Weather Data
   * 
   * Calls the fetch-weather edge function to get real-time weather data
   * for the user's location. Weather data is fetched from an external API
   * and includes temperature, humidity, conditions, and wind speed.
   * 
   * @param location - User's location/region (e.g., "Nairobi, Kenya")
   * 
   * Error Handling:
   * - On API failure, falls back to default weather values
   * - Shows toast notification to inform user of degraded data
   * - Always sets weatherLoading to false to prevent infinite spinner
   * 
   * Why This Matters:
   * - Weather is crucial for farming decisions (planting, harvesting, irrigation)
   * - Real-time data helps farmers plan daily activities
   * - Integrated into AI insights for contextual recommendations
   */
  const fetchWeather = async (location: string) => {
    try {
      // Invoke edge function with user's location
      const { data, error } = await supabase.functions.invoke("fetch-weather", {
        body: { location },
      });

      if (error) throw error;
      setWeather(data);
    } catch (error) {
      console.error("Weather fetch error:", error);
      
      // Inform user that weather data is unavailable
      toast({
        title: "Weather Unavailable",
        description: "Using default weather data",
        variant: "destructive",
      });
      
      // Fallback to default weather values
      // These are reasonable defaults for Kenya's climate
      setWeather({ 
        temp: 24,                    // Default temperature in Celsius
        humidity: 65,                // Default humidity percentage
        condition: "Partly Cloudy",  // Generic weather condition
        windSpeed: 12                // Default wind speed in km/h
      });
    } finally {
      // Always stop loading spinner, even on error
      setWeatherLoading(false);
    }
  };

  /**
   * Fetch Active Crops
   * 
   * Retrieves all active crop plantings for the current user.
   * Only fetches crops with status="active" to exclude harvested crops.
   * 
   * Query Details:
   * - Filters by user_id to get only current user's crops
   * - Filters by status="active" to exclude harvested/inactive crops
   * - Orders by planting_date descending (most recent first)
   * 
   * Why This Matters:
   * - Crops are the foundation of farming operations
   * - Used in "My Produce" section to show current plantings
   * - Referenced by AI insights for harvest timing recommendations
   * - Critical for marketplace listing and selling decisions
   */
  const fetchCrops = async () => {
    // Get currently authenticated user
    const { data: { user } } = await supabase.auth.getUser();
    
    if (user) {
      // Query crops table with filters
      const { data } = await supabase
        .from("crops")
        .select("*")
        .eq("user_id", user.id)          // Only current user's crops
        .eq("status", "active")          // Only active crops (not harvested)
        .order("planting_date", { ascending: false }); // Most recent first
      
      if (data) setCrops(data);
    }
  };

  /**
   * Fetch Ledger Summary
   * 
   * Aggregates all financial transactions for the current user to calculate
   * total income, total expenses, and net profit.
   * 
   * Calculation Logic:
   * 1. Fetch all ledger entries for current user (no date filtering)
   * 2. Use reduce() to sum up income and expenses separately
   * 3. Net profit is derived from: totalIncome - totalExpenses
   * 
   * Data Structure:
   * - Each ledger entry has: type ("income" or "expense"), amount (number)
   * - Amounts are stored as numbers but cast to Number() for safety
   * 
   * Error Handling:
   * - Shows toast notification on database error
   * - Falls back to zero values on failure
   * - Prevents dashboard from breaking on financial data issues
   * 
   * Why This Matters:
   * - Financial tracking is core to farm business management
   * - Helps farmers understand profitability
   * - Used in both summary card and financial overview chart
   * - Critical for business planning and decision-making
   */
  const fetchLedgerSummary = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      // Fetch all ledger entries for current user
      // Only selecting type and amount for efficiency (don't need other fields)
      const { data, error } = await supabase
        .from('ledger')
        .select('type, amount')
        .eq('user_id', user.id);

      if (error) throw error;

      // Aggregate financial data using reduce
      // Separate totaling for income vs expenses
      const summary = data?.reduce(
        (acc, item) => {
          if (item.type === 'income') {
            // Add to income total
            acc.totalIncome += Number(item.amount);
          } else {
            // Add to expenses total (type === 'expense')
            acc.totalExpenses += Number(item.amount);
          }
          return acc;
        },
        { totalIncome: 0, totalExpenses: 0 } // Initial accumulator values
      );

      // Update state with calculated summary
      setLedgerSummary(summary || { totalIncome: 0, totalExpenses: 0 });
    } catch (error) {
      console.error('Error fetching ledger:', error);
      
      // Show user-friendly error message
      toast({
        title: "Error",
        description: "Failed to fetch financial data",
        variant: "destructive",
      });
    }
  };

  /**
   * Fetch AI Insights
   * 
   * Generates personalized, actionable farming recommendations using Lovable AI.
   * The edge function analyzes the user's complete farming profile including:
   * - Current crop plantings (types, planting dates, acreage)
   * - Financial history (income, expenses, profitability)
   * - Weather conditions (current and forecast)
   * - Market prices (current rates, recent changes)
   * - User stats (level, streak, engagement)
   * 
   * AI Processing:
   * 1. Edge function gathers all relevant user data from database
   * 2. Constructs context-rich prompt for AI model
   * 3. AI generates 3-5 specific, actionable recommendations
   * 4. Insights are prioritized by relevance and urgency
   * 
   * Insight Types:
   * - Harvest timing recommendations
   * - Planting suggestions based on season/weather
   * - Market timing advice (when to sell)
   * - Risk warnings (weather threats, pest alerts)
   * - Financial optimization tips
   * 
   * Fallback Behavior:
   * - On API failure, provides generic but useful farming advice
   * - Ensures dashboard always has content even if AI unavailable
   * - Fallback insights cover common farming best practices
   * 
   * Why This Matters:
   * - AI insights are a key differentiator for shambaXchange
   * - Provides expert-level farming advice to all users
   * - Helps farmers optimize yields and profitability
   * - Drives daily engagement through valuable content
   */
  const fetchAIInsights = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      // Invoke ai-insights edge function
      // Function will gather all user data and generate personalized insights
      const { data, error } = await supabase.functions.invoke("ai-insights", {
        body: { userId: user.id },
      });

      if (error) throw error;
      
      // Update state with AI-generated insights
      if (data?.insights) {
        setAiInsights(data.insights);
      }
    } catch (error) {
      console.error("AI insights error:", error);
      
      // Fallback to generic farming best practices
      // These are always relevant even without personalization
      setAiInsights([
        "Check weather conditions before planning your week's activities",
        "Monitor your crop health regularly for optimal yields",
        "Review current market prices to identify selling opportunities"
      ]);
    }
  };

  // ========================================
  // QUICK ACTIONS CONFIGURATION
  // ========================================
  
  /**
   * Quick Actions Menu
   * 
   * Provides fast access to frequently used dashboard features.
   * Each action includes an icon, label, color scheme, and click handler.
   * 
   * Actions:
   * 1. Yield Calculator - Helps farmers estimate crop yields based on acreage
   * 2. Add Expense/Income - Quick entry for financial transactions
   * 3. Learning Hub - Access to farming education and best practices
   * 4. Market Prices - Navigate to market intelligence page for pricing data
   * 
   * Design Pattern:
   * - Icon-based for quick recognition
   * - Color-coded for visual differentiation
   * - Opens relevant dialog or navigates to page
   */
  const quickActions = [
    { 
      icon: Calculator, 
      label: "Yield Calculator", 
      color: "bg-primary", 
      action: () => setYieldCalculatorOpen(true) 
    },
    { 
      icon: DollarSign, 
      label: "Add Expense/Income", 
      color: "bg-secondary", 
      action: () => setAddLedgerOpen(true) 
    },
    { 
      icon: BookOpen, 
      label: "Learning Hub", 
      color: "bg-accent", 
      action: () => navigate("/learning") 
    },
    { 
      icon: TrendingUp, 
      label: "Market Prices", 
      color: "bg-success", 
      action: () => navigate("/market-intel") 
    },
  ];

  // ========================================
  // COMPONENT RENDERING
  // ========================================
  
  /**
   * Dashboard Layout Structure:
   * 
   * 1. Header Section:
   *    - Personalized greeting with user's name
   *    - Location display
   *    - Real-time weather card (temp, humidity, wind speed)
   * 
   * 2. Quick Actions Grid:
   *    - 4 icon-based action buttons
   *    - Responsive: 2 columns on mobile, 4 on desktop
   * 
   * 3. AI Insights Card:
   *    - Displays 3-5 personalized farming recommendations
   *    - Generated by AI based on user's complete farming profile
   *    - Shows "No insights available" if AI response is empty
   * 
   * 4. My Produce Section:
   *    - Component showing active crop plantings
   *    - Quick add button integrated
   * 
   * 5. Financial Summary Card:
   *    - Total expenses, income, and net profit
   *    - Color-coded: red for expenses, green for income/profit
   *    - Quick add entry button
   * 
   * 6. Financial Overview Chart:
   *    - Bar chart visualizing expenses, income, and net profit
   *    - Responsive and themed to match design system
   * 
   * 7. Dialogs:
   *    - Add Crop Dialog (modal)
   *    - Add Ledger Entry Dialog (modal)
   *    - Yield Calculator Dialog (modal)
   *    - AI Chatbot (fixed position)
   * 
   * Responsive Design:
   * - Mobile: Single column, stacked layout, bottom padding for nav
   * - Desktop: Multi-column grids where appropriate, no bottom padding
   */
  return (
    <div className="space-y-6 pb-20 md:pb-6">
      {/* Header with greeting and weather */}
      <div className="flex flex-col gap-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          {/* User greeting and location */}
          <div>
            <h1 className="text-3xl font-bold text-foreground">
              Hi, {profile?.full_name || "Farmer"} 👋
            </h1>
            <p className="text-muted-foreground">{profile?.location || "Kenya"}</p>
          </div>
          
          {/* Real-time weather display */}
          <Card className="w-full sm:w-auto">
            <CardContent className="p-4 flex items-center gap-4">
              {weatherLoading ? (
                /* Show loading spinner while weather is being fetched */
                <Loader2 className="w-8 h-8 text-accent animate-spin" />
              ) : (
                <>
                  {/* Weather icon */}
                  <Cloud className="w-8 h-8 text-accent" />
                  
                  {/* Temperature and condition */}
                  <div>
                    <p className="font-semibold text-lg">{weather?.temp || 24}°C</p>
                    <p className="text-sm text-muted-foreground">{weather?.condition || "Partly Cloudy"}</p>
                  </div>
                  
                  {/* Humidity and wind speed */}
                  <div className="flex gap-2 text-muted-foreground">
                    <div className="flex items-center gap-1">
                      <Droplets className="w-4 h-4" />
                      <span className="text-sm">{weather?.humidity || 65}%</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Wind className="w-4 h-4" />
                      <span className="text-sm">{Math.round(weather?.windSpeed || 12)}km/h</span>
                    </div>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Quick Actions Grid - 2 columns mobile, 4 columns desktop */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {quickActions.map((action, idx) => (
            <Button
              key={idx}
              variant="outline"
              className="h-auto flex-col gap-2 p-6 hover:shadow-md transition-shadow"
              onClick={action.action}
            >
              {/* Colored icon circle */}
              <div className={`${action.color} p-3 rounded-full`}>
                <action.icon className="w-6 h-6 text-white" />
              </div>
              <span className="font-medium text-sm">{action.label}</span>
            </Button>
          ))}
        </div>
      </div>

      {/* Main content grid - 2 columns on desktop, single column on mobile */}
      <div className="grid gap-6 md:grid-cols-2">
        
        {/* AI Recommendations Card */}
        {/* 
         * Displays personalized farming insights generated by AI
         * 
         * Data Source: ai-insights edge function
         * 
         * Insight Generation Process:
         * 1. Edge function analyzes user's complete profile:
         *    - Crops (types, planting dates, acreage)
         *    - Financial history (income/expense patterns)
         *    - Weather conditions and forecasts
         *    - Market prices and trends
         *    - User stats and engagement level
         * 
         * 2. AI model (via Lovable AI) generates 3-5 actionable recommendations:
         *    - Harvest timing optimization
         *    - Planting schedule suggestions
         *    - Market timing advice (when to sell)
         *    - Risk warnings (weather, pests, diseases)
         *    - Financial optimization tips
         * 
         * 3. Insights are ranked by:
         *    - Urgency (time-sensitive actions first)
         *    - Impact (high-value opportunities prioritized)
         *    - Relevance (matched to user's current crops/situation)
         * 
         * Empty State:
         * Shows prompt to add crops and financial data when no insights available
         * This encourages user engagement and data input
         */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="w-5 h-5" />
              AI Recommendations
            </CardTitle>
            <CardDescription>Personalized insights based on your crops, location, and market data</CardDescription>
          </CardHeader>
          <CardContent>
            {aiInsights.length > 0 ? (
              /* Display each AI-generated insight in a styled card */
              <div className="space-y-3">
                {aiInsights.map((insight, idx) => (
                  <div 
                    key={idx} 
                    className="p-4 bg-primary/10 rounded-lg border-l-4 border-primary"
                  >
                    <p className="text-sm text-muted-foreground">{insight}</p>
                  </div>
                ))}
              </div>
            ) : (
              /* Empty state: Encourage user to add data for insights */
              <p className="text-sm text-muted-foreground">
                Add your crops and financial data to receive personalized AI recommendations.
              </p>
            )}
          </CardContent>
        </Card>

        {/* My Produce Component - Shows active crop plantings */}
        {/* 
         * Integrated component that displays user's active crops
         * Provides quick add button to open Add Crop dialog
         */}
        <MyProduce onAddClick={() => setAddCropOpen(true)} />

        {/* Financial Summary Card */}
        {/* 
         * Displays aggregated financial data from ledger table
         * 
         * Calculations:
         * - Total Expenses: Sum of all ledger entries where type='expense'
         * - Total Income: Sum of all ledger entries where type='income'
         * - Net Profit: totalIncome - totalExpenses
         * 
         * Color Coding:
         * - Expenses: Red (destructive color)
         * - Income: Green (success color)
         * - Net Profit: Green if positive, Red if negative
         * 
         * User Actions:
         * - "Add Entry" button opens Add Ledger Dialog
         * - Allows quick recording of new income/expense transactions
         */}
        <Card>
          <CardHeader>
            <CardTitle>Financial Summary</CardTitle>
            <CardDescription>Track your farm expenses and income</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* Total Expenses Row */}
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Total Expenses</span>
                <span className="font-bold text-destructive">
                  KES {ledgerSummary.totalExpenses.toLocaleString()}
                </span>
              </div>
              
              {/* Total Income Row */}
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Total Income</span>
                <span className="font-bold text-success">
                  KES {ledgerSummary.totalIncome.toLocaleString()}
                </span>
              </div>
              
              {/* Net Profit Row - Dynamic color based on positive/negative */}
              <div className="flex justify-between items-center pt-4 border-t">
                <span className="font-medium">Net Profit</span>
                <span className={`font-bold text-lg ${
                  ledgerSummary.totalIncome - ledgerSummary.totalExpenses >= 0 
                    ? "text-success"   // Green for profit
                    : "text-destructive" // Red for loss
                }`}>
                  KES {(ledgerSummary.totalIncome - ledgerSummary.totalExpenses).toLocaleString()}
                </span>
              </div>
              
              {/* Quick Add Entry Button */}
              <Button variant="outline" className="w-full" onClick={() => setAddLedgerOpen(true)}>
                Add Entry
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Financial Overview Chart */}
        {/* 
         * Visual representation of financial data using bar chart
         * Helps farmers quickly understand their financial position
         * 
         * Chart Configuration:
         * - Library: Recharts (responsive charting library)
         * - Type: Bar chart with 3 bars
         * - Height: 250px fixed height
         * - Width: 100% responsive to container
         * 
         * Data Bars:
         * 1. Expenses Bar (Red)
         *    - Value: totalExpenses from ledger summary
         *    - Color: Destructive theme color (red)
         * 
         * 2. Income Bar (Green)
         *    - Value: totalIncome from ledger summary
         *    - Color: Success theme color (green)
         * 
         * 3. Net Profit Bar (Dynamic Color)
         *    - Value: totalIncome - totalExpenses
         *    - Color: Green if positive, Red if negative
         *    - Provides instant visual feedback on profitability
         * 
         * Chart Features:
         * - Grid lines for easier value reading
         * - Y-axis formatted as thousands (e.g., "50K" instead of "50000")
         * - Tooltip shows full values with currency formatting
         * - Themed to match application design system
         * - Rounded bar tops for modern appearance
         * 
         * User Benefits:
         * - Quick visual comparison of income vs expenses
         * - Instant profitability assessment
         * - Professional financial reporting
         */}
        <Card>
          <CardHeader>
            <CardTitle>Financial Overview</CardTitle>
            <CardDescription>Visual breakdown of your farm finances</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={250}>
              <BarChart 
                data={[
                  {
                    name: 'Expenses',
                    amount: ledgerSummary.totalExpenses,
                    fill: 'hsl(var(--destructive))' // Red bar for expenses
                  },
                  {
                    name: 'Income',
                    amount: ledgerSummary.totalIncome,
                    fill: 'hsl(var(--success))'  // Green bar for income
                  },
                  {
                    name: 'Net Profit',
                    amount: ledgerSummary.totalIncome - ledgerSummary.totalExpenses,
                    // Dynamic color: Green if profit, Red if loss
                    fill: ledgerSummary.totalIncome - ledgerSummary.totalExpenses >= 0 
                      ? 'hsl(var(--success))' 
                      : 'hsl(var(--destructive))'
                  }
                ]}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                {/* Grid lines for easier value reading */}
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                
                {/* X-axis: Category names (Expenses, Income, Net Profit) */}
                <XAxis 
                  dataKey="name" 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                />
                
                {/* Y-axis: Financial amounts in thousands */}
                <YAxis 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                  tickFormatter={(value) => `${(value / 1000).toFixed(0)}K`} // Format as "50K"
                />
                
                {/* Tooltip: Shows full amount on hover */}
                <Tooltip 
                  formatter={(value: number) => `KES ${value.toLocaleString()}`}
                  contentStyle={{
                    backgroundColor: 'hsl(var(--background))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                />
                
                {/* Bar component with rounded tops */}
                <Bar 
                  dataKey="amount" 
                  radius={[8, 8, 0, 0]} // Rounded top corners
                />
              </BarChart>
            </ResponsiveContainer>
            
            {/* Financial Summary Grid Below Chart */}
            {/* 
             * Provides exact numerical values to complement visual chart
             * 3-column grid showing Expenses, Income, and Net Profit
             * Allows precise value reading alongside chart visualization
             */}
            <div className="mt-4 grid grid-cols-3 gap-4 text-center">
              {/* Expenses Column */}
              <div>
                <p className="text-xs text-muted-foreground">Expenses</p>
                <p className="text-sm font-bold text-destructive">
                  KES {ledgerSummary.totalExpenses.toLocaleString()}
                </p>
              </div>
              
              {/* Income Column */}
              <div>
                <p className="text-xs text-muted-foreground">Income</p>
                <p className="text-sm font-bold text-success">
                  KES {ledgerSummary.totalIncome.toLocaleString()}
                </p>
              </div>
              
              {/* Net Profit Column */}
              <div>
                <p className="text-xs text-muted-foreground">Net Profit</p>
                <p className={`text-sm font-bold ${
                  ledgerSummary.totalIncome - ledgerSummary.totalExpenses >= 0 
                    ? "text-success" 
                    : "text-destructive"
                }`}>
                  KES {(ledgerSummary.totalIncome - ledgerSummary.totalExpenses).toLocaleString()}
                </p>
              </div>
            </div>
            
            {/* View Detailed Breakdown Button */}
            {/* 
             * Navigates to dedicated Finances page (/finances)
             * Provides access to:
             * - Full transaction history
             * - Advanced filtering and analysis
             * - Detailed expense categorization
             * - Export capabilities
             */}
            <Button 
              variant="outline" 
              className="w-full mt-4"
              onClick={() => navigate("/finances")}
            >
              <Calculator className="w-4 h-4 mr-2" />
              View Detailed Breakdown
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* ========================================
       * MODAL DIALOGS
       * ========================================
       * 
       * These dialog components are rendered but initially hidden.
       * They appear as modals when their respective 'open' state is true.
       * Each dialog has its own state management and callbacks.
       */}
      
      {/* Yield Calculator Dialog */}
      {/* 
       * Helps farmers estimate expected crop yields based on:
       * - Crop type
       * - Acreage planted
       * - Regional averages
       * - Growing conditions
       */}
      <YieldCalculatorDialog 
        open={yieldCalculatorOpen} 
        onOpenChange={setYieldCalculatorOpen}
      />
      
      {/* Add Crop Dialog */}
      {/* 
       * Form for adding new crop plantings
       * Fields: crop name, planting date, acreage, expected yield
       * 
       * onSuccess callback:
       * - Refreshes crops list after successful addition
       * - Updates "My Produce" section immediately
       */}
      <AddCropDialog 
        open={addCropOpen} 
        onOpenChange={setAddCropOpen}
        onSuccess={fetchCrops} // Refresh crops list after adding
      />
      
      {/* Add Ledger Entry Dialog */}
      {/* 
       * Form for recording financial transactions
       * Fields: type (income/expense), date, item, amount, quantity, notes
       * 
       * onSuccess callback:
       * - Recalculates financial summary
       * - Updates both Financial Summary card and chart
       */}
      <AddLedgerDialog 
        open={addLedgerOpen} 
        onOpenChange={setAddLedgerOpen}
        onSuccess={fetchLedgerSummary} // Refresh financial data after adding
      />
      
      {/* AI Chatbot Component */}
      {/* 
       * Fixed-position AI assistant (Ask Shamba)
       * Provides real-time farming advice and answers
       * Available on all dashboard pages
       * Uses Lovable AI for intelligent responses
       */}
      <AIChatbot />
    </div>
  );
};

export default Dashboard;
